version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/acebook
file_exists_behaviour: OVERWRITE
permissions:
  - object: /home/ec2-user/acebook
    pattern: "**"
    owner: ec2-user
    group: wheel
    mode: 777
hooks:
  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: ec2-user
