version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/aws-codedeploy
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 300
      runas: ec2-user

