POST http://localhost:3030/api/user/new
Content-Type: application/json

{
  "firstName": "tanil",
  "lastName": "serbes",
  "email": "t1@gmail.com",
  "password": "1234"
}

###
POST http://localhost:3030/api/user/login
Content-Type: application/json

{
  "email": "t1@gmail.com",
  "password": "1234"
}

###
get http://localhost:3030/api/user/verify?token=ee29fbc611c345f0cd109af

Content-Type: application/json





