POST http://localhost:3030/api/user/new
Content-Type: application/json

{
  "firstName": "tanil",
  "lastName": "serbes",
  "email": "serbe34116s@gmail.com",
  "password": "1234"
}

###
POST http://localhost:3030/api/user/login
Content-Type: application/json

{
  "email": "srbe3411s@gmail.com",
  "password": "1234"
}

