name: CICD Testing Workflow
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' 
  
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '5.0'

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
            build: npm run build
            start: npm start
            wait-on: http://localhost:3030
      
      - name: Install Dependencies
        run: npm install

      - name: Run Lint 
        run: npm run lint 

      - name: Run Test:Unit
        run: npm run test:unit    
