name: Deploy

on:
  workflow_run:
    workflows: [Build and Test]
    branches: [main]
    types: [completed]

jobs:
  print-message:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Print a confirmation message
        run: echo This message should only be visible when tests pass
